export const phraseMap: Record<string, string> = {
  female_presenting: "woman",
  male_presenting: "man",
  androgynous: "androgynous person",
  non_binary_presenting: "non-binary presenting person",

  very_light: "very light skin",
  light: "light skin",
  light_olive: "light olive skin",
  medium: "medium skin",
  medium_olive: "medium olive skin",
  medium_brown: "medium brown skin",
  dark_brown: "dark brown skin",
  deep_brown: "deep brown skin",
  very_deep_brown: "very deep brown skin",

  cool: "cool undertones",
  neutral: "neutral undertones",
  warm: "warm undertones",
  olive: "olive undertones",
  golden: "golden undertones",
  red: "subtle red undertones",

  oval: "oval face",
  round: "round face",
  square: "square face",
  rectangular: "rectangular face",
  heart_shaped: "heart-shaped face",
  diamond: "diamond-shaped face",
  long: "long face",
  broad: "broad face",

  oval_head: "oval head shape",
  round_head: "rounded head shape",
  long_head: "long head shape",
  broad_head: "broad head shape",
  narrow_head: "narrow head shape",
  high_cranium: "slightly high cranium",
  low_cranium: "slightly low cranium",

  natural_pores: "natural visible pores",
  visible_pores: "visible pores",
  fine_texture: "fine realistic skin texture",
  rough_texture: "slightly rough skin texture",
  mature_skin_texture: "mature skin texture",
  sun_damaged_texture: "subtle sun-damaged texture",

  straight_soft_brows: "straight soft eyebrows",
  softly_arched_brows: "softly arched eyebrows",
  defined_arched_brows: "defined arched eyebrows",
  full_natural_brows: "full natural eyebrows",
  feathered_brows: "feathered eyebrows",
  low_straight_brows: "low straight eyebrows",

  straight: "straight",
  wavy: "wavy",
  curly: "curly",
  coily: "coily",
  kinky_coily: "tightly coiled",

  shaved: "shaved",
  buzz_cut: "buzz-cut",
  short: "short",
  medium: "medium-length",
  shoulder_length: "shoulder-length",
  long: "long",
  very_long: "very long",

  black: "black",
  dark_brown: "dark brown",
  brown: "brown",
  light_brown: "light brown",
  dark_blonde: "dark blonde",
  blonde: "blonde",
  red_hair: "red",
  gray: "gray",
  white: "white",
  dyed_color: "subtly dyed",

  clean_shaved_head: "a clean shaved head",
  buzz_cut_fade: "a close buzz cut with a clean fade",
  textured_crop: "a short textured crop",
  textured_pixie_cut: "a textured pixie cut with piece-y layers",
  short_side_part: "a neat short cut with a defined side part",
  slicked_back_short_style: "a slicked-back short style",
  jaw_length_blunt_bob: "a jaw-length blunt bob",
  layered_bob_with_curtain_bangs: "a layered bob with soft curtain bangs",
  shaggy_long_bob: "a shoulder-length long bob with choppy shag layers",
  shoulder_length_layered_cut: "a shoulder-length layered cut with face-framing pieces",
  collarbone_straight_layers: "a collarbone-length layered cut with a mostly straight fall",
  soft_waves_center_part: "soft waves with a center part",
  long_loose_straight_layers: "long loose layers with an almost-straight fall",
  smooth_long_face_framing_layers: "smooth long layers with soft face-framing pieces",
  long_soft_blowout_layers: "long soft blowout layers",
  long_face_framing_layers: "long face-framing layers with a center part",
  sleek_low_ponytail: "a sleek low ponytail",
  messy_top_knot: "a messy top knot with loose tendrils",
  braided_crown_updo: "a braided crown updo",
  defined_natural_curl_shape: "a defined natural curl shape",
  tapered_coil_cut: "a tapered coil cut",
  two_strand_twists: "two-strand twists",
  box_braids: "box braids",
  locs_pulled_back: "locs pulled back from the face",
  flat_twist_bun: "a flat-twist bun",

  center_part: "a center part",
  soft_off_center_part: "a soft off-center part",
  deep_side_part: "a deep side part",
  broken_center_part: "a slightly broken center part",
  loose_side_sweep: "a loose side sweep",
  tucked_behind_one_ear: "one side loosely tucked behind the ear",
  brushed_back_off_face: "brushed back off the face",
  no_defined_part: "no strongly defined part",
  parting_not_visible: "",

  smooth_polished_finish: "a smooth polished finish",
  soft_natural_blowout: "a soft natural blowout finish",
  air_dried_lived_in_texture: "a lived-in air-dried texture",
  subtle_bend_through_lengths: "a subtle bend through the lengths",
  natural_body_and_movement: "natural body and movement",
  piecey_tousled_texture: "a lightly piece-y tousled texture",
  sleek_mostly_straight_finish: "a sleek mostly straight finish",
  finish_not_emphasized: "",

  full_hairline: "a full natural hairline",
  mature_hairline: "a slightly mature hairline",
  slightly_receding_hairline: "a subtly receding hairline at the temples",
  receding_hairline: "a clearly receding hairline",
  thinning_crown: "visible thinning at the crown",
  balding_top: "significant thinning on top with a bald crown area",
  closely_shaved_balding: "a closely shaved balding scalp",
  clean_shaved_bald: "a fully bald scalp",

  clean_shaven_face: "a clean-shaven face",
  faint_mustache_shadow: "a faint mustache shadow",
  light_stubble: "light stubble",
  medium_stubble: "medium stubble",
  short_boxed_beard: "a short boxed beard",
  goatee: "a neat goatee",
  trimmed_mustache: "a trimmed mustache",
  mustache_with_stubble: "a mustache with light stubble",
  salt_and_pepper_beard: "a salt-and-pepper beard",

  no_eyewear: "",
  thin_metal_round_glasses: "thin round metal glasses",
  soft_rectangular_acetate_glasses: "soft rectangular acetate glasses",
  clear_frame_glasses: "clear-frame glasses",
  wireframe_oval_glasses: "wireframe oval glasses",
  subtle_cat_eye_glasses: "subtle cat-eye glasses",
  simple_reading_glasses: "simple reading glasses",
  modern_rectangular_glasses: "modern rectangular glasses",

  small_lobe_studs: "small lobe studs",
  small_hoop_earrings: "small hoop earrings",
  multiple_lobe_piercings: "multiple lobe piercings",
  single_helix_piercing: "a single helix piercing",
  double_helix_piercing: "double helix piercings",
  nostril_stud: "a nostril stud",
  septum_ring: "a subtle septum ring",
  eyebrow_piercing: "an eyebrow piercing",
  small_nose_ring: "a small nose ring",
  subtle_lip_ring: "a subtle lip ring",

  no_visible_jewelry: "",
  fine_gold_chain: "a fine gold chain",
  small_pendant_necklace: "a small pendant necklace",
  simple_silver_chain: "a simple silver chain",
  small_pearl_earrings: "small pearl earrings",
  small_gold_hoops: "small gold hoops",
  minimalist_ear_cuff: "a minimalist ear cuff",
  beaded_necklace: "a beaded necklace",
  layered_delicate_necklaces: "layered delicate necklaces",
  signet_ring_visible_near_face: "a signet ring occasionally visible near the face",

  small_fine_line_neck_tattoo: "a small fine-line tattoo on the side of the neck",
  subtle_behind_ear_tattoo: "a subtle tattoo behind one ear",
  small_collarbone_script_tattoo: "a small script tattoo along the collarbone",
  minimal_blackwork_neck_tattoo: "a minimal blackwork tattoo at the neck",
  tiny_star_tattoo_near_neckline: "a tiny star tattoo near the neckline",
  small_botanical_tattoo_at_collarbone: "a small botanical tattoo at the collarbone",
  micro_symbol_tattoo_behind_ear: "a micro symbol tattoo behind the ear",

  no_visible_scars: "",
  faint_eyebrow_scar: "a faint healed eyebrow scar",
  small_chin_scar: "a small healed chin scar",
  faint_scar_near_upper_lip: "a faint scar near the upper lip",
  subtle_temple_scar: "a subtle scar near one temple",
  small_healed_forehead_line: "a small healed line on the forehead",
  soft_jawline_scar: "a soft healed scar along the jawline",

  no_specific_cultural_styling: "",
  neatly_draped_headscarf: "a neatly draped headscarf",
  printed_headwrap: "a printed headwrap",
  simple_turban_wrap: "a simple turban wrap",
  embroidered_collar_detail: "an embroidered collar detail",
  traditional_textile_scarf_detail: "a traditional textile scarf detail",
  modest_draped_shoulder_scarf: "a modest draped shoulder scarf",

  faint_freckles_across_nose: "faint freckles across the nose",
  single_beauty_mark_on_cheek: "a single beauty mark on the cheek",
  subtle_eyebrow_scar: "a subtle eyebrow scar",
  soft_dimples: "soft dimples",
  slight_under_eye_hollows: "slight under-eye hollows",
  rosy_cheeks: "rosy cheeks",
  slightly_chapped_lips: "slightly chapped lips",
  sun_touched_freckles: "sun-touched freckles",
  one_crooked_front_tooth: "one slightly crooked front tooth",

  masculine_coded: "masculine-coded",
  feminine_coded: "feminine-coded",
  neutral_coded: "neutral-coded",

  blue: "blue",
  green: "green",
  hazel: "hazel",
  gray_eyes: "gray",
  brown_eyes: "brown",

  nearly_symmetrical_with_minor_variation: "a nearly symmetrical face with minor natural variation",
  subtle_left_right_facial_asymmetry: "subtle natural asymmetry between the left and right sides of the face",
  slight_brow_height_asymmetry: "a slight difference in brow height from one side to the other",
  slight_eye_opening_asymmetry: "a slight difference in eye openness between both sides",
  slight_mouth_corner_asymmetry: "a slightly uneven set to the corners of the mouth",

  soft_open_expression: "a soft open expression",
  relaxed_neutral_expression: "a relaxed neutral expression",
  faint_closed_mouth_smile: "a faint closed-mouth smile",
  curious_attentive_expression: "a curious attentive expression",
  thoughtful_quiet_expression: "a thoughtful quiet expression",
  subtle_half_smile: "a subtle half-smile",
  composed_serious_expression: "a composed serious expression",

  direct_camera_gaze: "a direct gaze into the camera",
  slightly_off_camera_gaze: "a gaze slightly off camera",
  soft_side_glance: "a soft side glance",
  lowered_thoughtful_gaze: "a slightly lowered thoughtful gaze",

  straight_on_head_position: "a straight-on head position",
  slight_head_tilt: "a slight head tilt",
  subtle_three_quarter_turn: "a subtle three-quarter turn",
  slight_chin_down: "the chin held slightly down",
  slight_chin_up: "the chin lifted slightly up",
  gentle_head_turn_with_tilt: "a gentle head turn with a slight tilt",

  almond: "almond-shaped eyes",
  round_eyes: "round eyes",
  narrow: "narrow eyes",
  deep_set: "deep-set eyes",
  wide_open: "wide-open eyes",
  sleepy: "slightly sleepy eyes",
  sharp: "sharp eyes",

  monolid: "monolid eyelids",
  tapered_double_lid: "tapered double eyelids",
  parallel_double_lid: "parallel double eyelids",
  visible_upper_lid: "visible upper eyelids",
  hooded_lid: "hooded eyelids",
  deep_crease: "deep eyelid crease",
  low_crease: "low eyelid crease",

  small: "small",
  medium_size: "medium",
  medium_large: "medium-large",
  large: "large",
  prominent: "prominent",

  straight_profile: "straight nose profile",
  soft_convex_profile: "softly convex nose profile",
  aquiline_profile: "softly aquiline nose",
  hooked_profile: "hooked nose profile",
  roman_profile: "Roman nose profile",
  button_nose: "button nose",
  upturned_nose: "slightly upturned nose",
  downturned_tip: "slightly downturned nose tip",
  broad_flat_bridge: "broad low nose bridge",
  low_bridge: "low nose bridge",
  medium_bridge: "medium nose bridge",
  soft_bridge: "soft nose bridge",
  slightly_crooked: "slightly asymmetrical nose",

  thin_lips: "thin lips",
  medium_lips: "medium lips",
  full_lips: "full lips",
  very_full_lips: "very full lips",

  flat_cheeks: "flat cheeks",
  subtle_fullness: "subtle cheek fullness",
  soft_fullness: "soft cheek fullness",
  full: "full cheeks",
  very_full: "very full cheeks",

  soft_jaw: "soft jawline",
  rounded_jaw: "rounded jaw",
  soft_square_jaw: "soft square jaw",
  angular_jaw: "angular jaw",
  narrow_jaw: "narrow jaw",
  broad_jaw: "broad jaw",

  none: "no visible",
  very_subtle: "very subtle",
  subtle: "subtle",
  moderate: "moderate",
  pronounced: "pronounced",
  deep: "deep"
};

export function phrase(key: string): string {
  return phraseMap[key] ?? key.replaceAll("_", " ");
}

export function commaList(items: string[]): string {
  if (items.length <= 1) return items.join("");
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(", ")}, and ${items[items.length - 1]}`;
}
