export const phraseMap: Record<string, string> = {
  female_presenting: "woman",
  male_presenting: "man",
  androgynous: "androgynous person",
  non_binary_presenting: "non-binary presenting person",

  very_light: "very light skin",
  light: "light skin",
  light_olive: "light olive skin",
  medium: "medium skin",
  medium_olive: "medium olive skin",
  medium_brown: "medium brown skin",
  dark_brown: "dark brown skin",
  deep_brown: "deep brown skin",
  very_deep_brown: "very deep brown skin",

  cool: "cool undertones",
  neutral: "neutral undertones",
  warm: "warm undertones",
  olive: "olive undertones",
  golden: "golden undertones",
  red: "subtle red undertones",

  oval: "oval face",
  round: "round face",
  square: "square face",
  rectangular: "rectangular face",
  heart_shaped: "heart-shaped face",
  diamond: "diamond-shaped face",
  long: "long face",
  broad: "broad face",

  oval_head: "oval head shape",
  round_head: "rounded head shape",
  long_head: "long head shape",
  broad_head: "broad head shape",
  narrow_head: "narrow head shape",
  high_cranium: "slightly high cranium",
  low_cranium: "slightly low cranium",

  natural_pores: "natural visible pores",
  visible_pores: "visible pores",
  fine_texture: "fine realistic skin texture",
  rough_texture: "slightly rough skin texture",
  mature_skin_texture: "mature skin texture",
  sun_damaged_texture: "subtle sun-damaged texture",

  straight_soft_brows: "straight soft eyebrows",
  softly_arched_brows: "softly arched eyebrows",
  defined_arched_brows: "defined arched eyebrows",
  full_natural_brows: "full natural eyebrows",
  feathered_brows: "feathered eyebrows",
  low_straight_brows: "low straight eyebrows",

  straight: "straight",
  wavy: "wavy",
  curly: "curly",
  coily: "coily",
  kinky_coily: "tightly coiled",

  shaved: "shaved",
  buzz_cut: "buzz-cut",
  short: "short",
  medium: "medium-length",
  shoulder_length: "shoulder-length",
  long: "long",
  very_long: "very long",

  black: "black",
  dark_brown: "dark brown",
  brown: "brown",
  light_brown: "light brown",
  dark_blonde: "dark blonde",
  blonde: "blonde",
  red_hair: "red",
  gray: "gray",
  white: "white",
  dyed_color: "subtly dyed",

  clean_shaved_head: "a clean shaved head",
  buzz_cut_fade: "a close buzz cut with a clean fade",
  textured_crop: "a short textured crop",
  textured_pixie_cut: "a textured pixie cut with piece-y layers",
  short_side_part: "a neat short cut with a defined side part",
  slicked_back_short_style: "a slicked-back short style",
  jaw_length_blunt_bob: "a jaw-length blunt bob",
  layered_bob_with_curtain_bangs: "a layered bob with soft curtain bangs",
  shaggy_long_bob: "a shoulder-length long bob with choppy shag layers",
  shoulder_length_layered_cut: "a shoulder-length layered cut with face-framing pieces",
  collarbone_straight_layers: "a collarbone-length layered cut with a mostly straight fall",
  soft_waves_center_part: "soft waves with a center part",
  long_loose_straight_layers: "long loose layers with an almost-straight fall",
  smooth_long_face_framing_layers: "smooth long layers with soft face-framing pieces",
  long_soft_blowout_layers: "long soft blowout layers",
  long_face_framing_layers: "long face-framing layers with a center part",
  sleek_low_ponytail: "a sleek low ponytail",
  messy_top_knot: "a messy top knot with loose tendrils",
  braided_crown_updo: "a braided crown updo",
  defined_natural_curl_shape: "a defined natural curl shape",
  tapered_coil_cut: "a tapered coil cut",
  two_strand_twists: "two-strand twists",
  box_braids: "box braids",
  locs_pulled_back: "locs pulled back from the face",
  flat_twist_bun: "a flat-twist bun",

  center_part: "a center part",
  soft_off_center_part: "a soft off-center part",
  deep_side_part: "a deep side part",
  broken_center_part: "a slightly broken center part",
  loose_side_sweep: "a loose side sweep",
  tucked_behind_one_ear: "one side loosely tucked behind the ear",
  brushed_back_off_face: "brushed back off the face",
  no_defined_part: "no strongly defined part",
  parting_not_visible: "",

  smooth_polished_finish: "a smooth polished finish",
  soft_natural_blowout: "a soft natural blowout finish",
  air_dried_lived_in_texture: "a lived-in air-dried texture",
  subtle_bend_through_lengths: "a subtle bend through the lengths",
  natural_body_and_movement: "natural body and movement",
  piecey_tousled_texture: "a lightly piece-y tousled texture",
  sleek_mostly_straight_finish: "a sleek mostly straight finish",
  finish_not_emphasized: "",

  full_hairline: "a full natural hairline",
  mature_hairline: "a slightly mature hairline",
  slightly_receding_hairline: "a subtly receding hairline at the temples",
  receding_hairline: "a clearly receding hairline",
  thinning_crown: "visible thinning at the crown",
  balding_top: "significant thinning on top with a bald crown area",
  closely_shaved_balding: "a closely shaved balding scalp",
  clean_shaved_bald: "a fully bald scalp",

  clean_shaven_face: "a clean-shaven face",
  faint_mustache_shadow: "a faint mustache shadow",
  soft_natural_mustache: "a soft natural mustache",
  thin_mustache: "a thin mustache",
  defined_mustache: "a defined mustache",
  chevron_mustache: "a short chevron mustache",
  light_stubble: "light stubble",
  medium_stubble: "medium stubble",
  heavy_stubble: "heavy stubble",
  patchy_stubble: "patchy stubble",
  jawline_stubble: "stubble mostly along the jawline",
  chin_stubble: "stubble concentrated around the chin",
  faint_mustache_with_light_stubble: "a faint mustache with light jaw stubble",
  soft_mustache_with_light_stubble: "a soft natural mustache with light stubble",
  defined_mustache_with_stubble: "a defined mustache with surrounding stubble",
  mustache_with_medium_stubble: "a mustache with medium stubble",
  soul_patch: "a small soul patch below the lower lip",
  short_boxed_beard: "a short boxed beard",
  goatee: "a neat goatee",
  trimmed_mustache: "a trimmed mustache",
  short_full_beard: "a short full beard",
  scruffy_short_beard: "a scruffy short beard",
  full_beard: "a full beard",
  mustache_with_stubble: "a mustache with light stubble",
  salt_and_pepper_beard: "a salt-and-pepper beard",

  no_eyewear: "",
  thin_metal_round_glasses: "thin round metal glasses",
  soft_rectangular_acetate_glasses: "soft rectangular acetate glasses",
  clear_frame_glasses: "clear-frame glasses",
  wireframe_oval_glasses: "wireframe oval glasses",
  subtle_cat_eye_glasses: "subtle cat-eye glasses",
  simple_reading_glasses: "simple reading glasses",
  modern_rectangular_glasses: "modern rectangular glasses",

  small_lobe_studs: "small lobe studs",
  small_hoop_earrings: "small hoop earrings",
  multiple_lobe_piercings: "multiple lobe piercings",
  single_helix_piercing: "a single helix piercing",
  double_helix_piercing: "double helix piercings",
  nostril_stud: "a nostril stud",
  septum_ring: "a subtle septum ring",
  eyebrow_piercing: "an eyebrow piercing",
  small_nose_ring: "a small nose ring",
  subtle_lip_ring: "a subtle lip ring",

  no_visible_jewelry: "",
  fine_gold_chain: "a fine gold chain",
  small_pendant_necklace: "a small pendant necklace",
  simple_silver_chain: "a simple silver chain",
  small_pearl_earrings: "small pearl earrings",
  small_gold_hoops: "small gold hoops",
  minimalist_ear_cuff: "a minimalist ear cuff",
  beaded_necklace: "a beaded necklace",
  layered_delicate_necklaces: "layered delicate necklaces",
  signet_ring_visible_near_face: "a signet ring occasionally visible near the face",

  small_fine_line_neck_tattoo: "a small fine-line tattoo on the side of the neck",
  subtle_behind_ear_tattoo: "a subtle tattoo behind one ear",
  small_collarbone_script_tattoo: "a small script tattoo along the collarbone",
  minimal_blackwork_neck_tattoo: "a minimal blackwork tattoo at the neck",
  tiny_star_tattoo_near_neckline: "a tiny star tattoo near the neckline",
  small_botanical_tattoo_at_collarbone: "a small botanical tattoo at the collarbone",
  micro_symbol_tattoo_behind_ear: "a micro symbol tattoo behind the ear",

  no_visible_scars: "",
  faint_eyebrow_scar: "a faint healed eyebrow scar",
  small_chin_scar: "a small healed chin scar",
  faint_scar_near_upper_lip: "a faint scar near the upper lip",
  subtle_temple_scar: "a subtle scar near one temple",
  small_healed_forehead_line: "a small healed line on the forehead",
  soft_jawline_scar: "a soft healed scar along the jawline",

  no_specific_cultural_styling: "",
  neatly_draped_headscarf: "a neatly draped headscarf",
  printed_headwrap: "a printed headwrap",
  simple_turban_wrap: "a simple turban wrap",
  embroidered_collar_detail: "an embroidered collar detail",
  traditional_textile_scarf_detail: "a traditional textile scarf detail",
  modest_draped_shoulder_scarf: "a modest draped shoulder scarf",

  faint_freckles_across_nose: "faint freckles across the nose",
  single_beauty_mark_on_cheek: "a single beauty mark on the cheek",
  subtle_eyebrow_scar: "a subtle eyebrow scar",
  soft_dimples: "soft dimples",
  slight_under_eye_hollows: "slight under-eye hollows",
  rosy_cheeks: "rosy cheeks",
  slightly_chapped_lips: "slightly chapped lips",
  sun_touched_freckles: "sun-touched freckles",
  one_crooked_front_tooth: "one slightly crooked front tooth",

  masculine_coded: "masculine-coded",
  feminine_coded: "feminine-coded",
  neutral_coded: "neutral-coded",

  blue: "blue",
  green: "green",
  hazel: "hazel",
  gray_eyes: "gray",
  brown_eyes: "brown",

  nearly_symmetrical_with_minor_variation: "a nearly symmetrical face with minor natural variation",
  subtle_left_right_facial_asymmetry: "subtle natural asymmetry between the left and right sides of the face",
  slight_brow_height_asymmetry: "a slight difference in brow height from one side to the other",
  slight_eye_opening_asymmetry: "a slight difference in eye openness between both sides",
  slight_mouth_corner_asymmetry: "a slightly uneven set to the corners of the mouth",

  soft_open_expression: "a soft open expression",
  relaxed_neutral_expression: "a relaxed neutral expression",
  faint_closed_mouth_smile: "a faint closed-mouth smile",
  curious_attentive_expression: "a curious attentive expression",
  thoughtful_quiet_expression: "a thoughtful quiet expression",
  subtle_half_smile: "a subtle half-smile",
  composed_serious_expression: "a composed serious expression",

  natural_everyday_presence: "a natural everyday presence",
  soft_approachable_presence: "a soft approachable presence",
  calm_confident_presence: "a calm confident presence",
  quiet_intense_presence: "a quiet intense presence",
  cool_detached_presence: "a cool detached presence",
  editorial_composed_presence: "an editorial composed presence",
  raw_street_casting_presence: "a raw street-casting presence",
  soft_gaze_intensity: "a soft gaze",
  neutral_gaze_intensity: "a neutral gaze intensity",
  focused_gaze_intensity: "a focused gaze",
  intense_gaze_intensity: "an intense direct gaze",
  distant_gaze_intensity: "a slightly distant gaze",
  relaxed_closed_mouth: "a relaxed closed mouth",
  neutral_closed_lips: "neutral closed lips",
  firm_closed_lips: "firm closed lips",
  slightly_pursed_lips: "slightly pursed lips",
  soft_hint_of_smile: "a soft hint of a smile",
  parted_relaxed_lips: "relaxed slightly parted lips",
  relaxed_brow_expression: "relaxed brows",
  subtle_brow_focus: "subtle focus in the brows",
  slight_brow_furrow: "a slight brow furrow",
  lifted_attentive_brows: "slightly lifted attentive brows",
  asymmetric_brow_interest: "a subtle asymmetric brow expression",
  intense_brow_tension: "visible brow tension",
  tight_headshot_framing: "tight headshot framing",
  head_and_shoulders_framing: "head-and-shoulders framing",
  medium_close_up_framing: "medium close-up framing",
  close_cropped_face_framing: "a close-cropped face framing",
  relaxed_portrait_crop: "a relaxed portrait crop",
  clean_commercial_casting: "clean commercial casting portrait style",
  natural_lifestyle_casting: "natural lifestyle casting portrait style",
  raw_editorial_casting: "raw editorial casting portrait style",
  cool_fashion_casting: "cool fashion casting portrait style",
  office_professional_casting: "office professional casting portrait style",
  character_extra_casting: "character extras casting portrait style",
  premium_minimal_casting: "premium minimal casting portrait style",

  direct_camera_gaze: "a direct gaze into the camera",
  slightly_off_camera_gaze: "a gaze slightly off camera",
  soft_side_glance: "a soft side glance",
  lowered_thoughtful_gaze: "a slightly lowered thoughtful gaze",

  straight_on_head_position: "a straight-on head position",
  slight_head_tilt: "a slight head tilt",
  subtle_three_quarter_turn: "a subtle three-quarter turn",
  slight_chin_down: "the chin held slightly down",
  slight_chin_up: "the chin lifted slightly up",
  gentle_head_turn_with_tilt: "a gentle head turn with a slight tilt",

  almond: "almond-shaped eyes",
  almond_eyes: "almond-shaped eyes",
  round_eyes: "round eyes",
  narrow: "narrow eyes",
  narrow_eyes: "narrow eyes",
  deep_set: "deep-set eyes",
  deep_set_eyes: "deep-set eyes",
  wide_open: "wide-open eyes",
  wide_open_eyes: "wide-open eyes",
  sleepy: "slightly sleepy eyes",
  sleepy_eyes: "slightly sleepy eyes",
  sharp: "sharp eyes",
  sharp_eyes: "sharp eyes",
  small_eyes: "small eyes",
  medium_eyes: "medium-sized eyes",
  large_eyes: "large eyes",
  very_large_eyes: "very large eyes",
  close_set_eyes: "close-set eyes",
  balanced_eye_spacing: "balanced eye spacing",
  wide_set_eyes: "wide-set eyes",
  neutral_canthal_tilt: "a neutral canthal tilt",
  slight_positive_canthal_tilt: "a slight upward tilt at the outer eye corners",
  slight_negative_canthal_tilt: "a slight downward tilt at the outer eye corners",
  level_outer_eye_corners: "level outer eye corners",
  smooth_under_eye_area: "a smooth under-eye area",
  soft_under_eye_fullness: "soft under-eye fullness",
  faint_under_eye_shadows: "faint under-eye shadows",
  visible_tear_troughs: "visible tear troughs",
  mild_under_eye_lines: "mild under-eye lines",

  monolid: "monolid eyelids",
  tapered_double_lid: "tapered double eyelids",
  parallel_double_lid: "parallel double eyelids",
  visible_upper_lid: "visible upper eyelids",
  hooded_lid: "hooded eyelids",
  deep_crease: "deep eyelid crease",
  low_crease: "low eyelid crease",

  sparse_brows: "sparser brow density",
  medium_density_brows: "medium-density brows",
  full_brows: "full brows",
  very_full_brows: "very full brows",
  low_set_brows: "low-set brows",
  balanced_brow_position: "a balanced brow position",
  high_set_brows: "slightly high-set brows",
  slightly_uneven_brow_position: "a subtly uneven brow position",
  soft_brow_ridge: "a soft brow ridge",
  subtle_brow_ridge: "a subtle brow ridge",
  defined_brow_ridge: "a defined brow ridge",
  prominent_brow_ridge: "a prominent brow ridge",

  small: "small",
  medium_size: "medium",
  medium_large: "medium-large",
  large: "large",
  prominent: "prominent",

  straight_profile: "straight nose profile",
  soft_convex_profile: "softly convex nose profile",
  aquiline_profile: "softly aquiline nose",
  hooked_profile: "hooked nose profile",
  roman_profile: "Roman nose profile",
  button_nose: "button nose",
  upturned_nose: "slightly upturned nose",
  downturned_tip: "slightly downturned nose tip",
  broad_flat_bridge: "broad low nose bridge",
  low_bridge: "low nose bridge",
  medium_bridge: "medium nose bridge",
  soft_bridge: "soft nose bridge",
  slightly_crooked: "slightly asymmetrical nose",
  short_nose: "short",
  medium_length_nose: "medium-length",
  long_nose: "long",
  very_long_nose: "very long",
  narrow_bridge: "a narrow nose bridge",
  medium_bridge_width: "a medium-width nose bridge",
  broad_bridge: "a broad nose bridge",
  softly_defined_bridge: "a softly defined nose bridge",
  rounded_nose_tip: "a rounded nose tip",
  softly_defined_nose_tip: "a softly defined nose tip",
  narrow_nose_tip: "a narrow nose tip",
  bulbous_nose_tip: "a softly bulbous nose tip",
  slightly_upturned_tip: "a slightly upturned nose tip",
  slightly_downturned_tip: "a slightly downturned nose tip",
  narrow_nostrils: "narrow nostrils",
  medium_nostril_width: "medium-width nostrils",
  broad_nostrils: "broad nostrils",
  flared_nostrils: "slightly flared nostrils",
  low_nostril_visibility: "low nostril visibility",
  moderate_nostril_visibility: "moderate nostril visibility",
  visible_nostril_openings: "visible nostril openings",

  thin_lips: "thin lips",
  medium_lips: "medium lips",
  full_lips: "full lips",
  very_full_lips: "very full lips",
  narrow_mouth: "a narrow mouth",
  medium_width_mouth: "a medium-width mouth",
  wide_mouth: "a wide mouth",
  very_wide_mouth: "a very wide mouth",
  softly_curved_mouth: "a softly curved mouth shape",
  straight_mouth_line: "a straighter mouth line",
  bow_shaped_mouth: "a bow-shaped mouth",
  full_rounded_mouth: "a full rounded mouth",
  asymmetrical_mouth_shape: "a subtly asymmetrical mouth shape",
  downturned_resting_mouth: "slightly downturned resting mouth corners",
  soft_cupid_bow: "a soft Cupid's bow",
  defined_cupid_bow: "a defined Cupid's bow",
  subtle_cupid_bow: "a subtle Cupid's bow",
  flat_upper_lip_bow: "a flatter upper-lip bow",
  short_philtrum: "a short philtrum",
  average_philtrum: "an average philtrum length",
  long_philtrum: "a long philtrum",
  very_long_philtrum: "a very long philtrum",
  gaunt_face: "a gaunt face with slightly hollow cheeks",
  lean_face: "a lean face with subtle cheek hollows",
  slim_face: "a slim face",
  average_facial_fullness: "average facial fullness",
  softly_full_face: "a softly full face",
  full_face: "a full face",
  very_full_face: "a very full face with a soft jawline",
  slender_visible_build: "a slender visible build",
  lean_visible_build: "a lean visible build",
  average_visible_build: "an average visible build",
  sturdy_visible_build: "a sturdy visible build",
  broad_visible_build: "a broad visible build",
  heavyset_visible_build: "a heavyset visible build",
  very_heavy_visible_build: "a very heavy visible build",

  flat_cheeks: "flat cheeks",
  subtle_fullness: "subtle cheek fullness",
  soft_fullness: "soft cheek fullness",
  full: "full cheeks",
  very_full: "very full cheeks",
  low_cheekbones: "low-set cheekbones",
  mid_set_cheekbones: "mid-set cheekbones",
  high_cheekbones: "high cheekbones",
  very_high_cheekbones: "very high cheekbones",
  soft_cheekbones: "soft cheekbones",
  subtle_cheekbone_definition: "subtle cheekbone definition",
  defined_cheekbones: "defined cheekbones",
  prominent_cheekbones: "prominent cheekbones",

  soft_jaw: "soft jawline",
  rounded_jaw: "rounded jaw",
  soft_square_jaw: "soft square jaw",
  angular_jaw: "angular jaw",
  narrow_jaw: "narrow jaw",
  broad_jaw: "broad jaw",
  softly_rounded_chin: "a softly rounded chin",
  balanced_chin: "a balanced chin",
  narrow_chin: "a narrow chin",
  broad_chin: "a broad chin",
  pointed_chin: "a softly pointed chin",
  cleft_chin: "a subtle cleft chin",
  low_forehead: "a lower forehead",
  balanced_forehead: "a balanced forehead height",
  high_forehead: "a higher forehead",
  broad_forehead: "a broad forehead",
  slender_neck: "a slender neck",
  average_neck_width: "an average neck width",
  sturdy_neck: "a sturdy neck",
  broad_neck: "a broad neck",
  soft_full_neck: "a softly full neck",
  narrow_shoulders: "narrow shoulders",
  average_shoulder_frame: "an average shoulder frame",
  gently_sloped_shoulders: "gently sloped shoulders",
  square_shoulders: "square shoulders",
  broad_shoulders: "broad shoulders",
  no_visible_freckles: "no visible freckles",
  light_cheek_freckles: "light freckles on the cheeks",
  scattered_face_freckles: "scattered freckles across the face",
  dense_freckles_across_face: "dense freckles across the face",

  none: "no visible",
  very_subtle: "very subtle",
  subtle: "subtle",
  moderate: "moderate",
  pronounced: "pronounced",
  deep: "deep"
};

export function phrase(key: string): string {
  return phraseMap[key] ?? key.replaceAll("_", " ");
}

export function commaList(items: string[]): string {
  if (items.length <= 1) return items.join("");
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(", ")}, and ${items[items.length - 1]}`;
}
